In [ ]:
##Projet de programmation PSY4016 - Traitement de données en neuroscience cognitive

In [31]:
#Importer la base de données
import pandas as pd
df = pd.read_spss(r"C:\Users\Dylan\Desktop\Honor\APES\ACE_COMBINED_Oct2020.sav")
df.head()

,UID,Sex,Age,Height,Weight,IMC,Group,Origine,Revenu_individuel,Revenu_fam,...,Age_OC_Bi,TIME_Réveil,TIME_30min,TIME_14h,TIME_16h,TIME_Bedtime,TIME_DIFF_Réveil_30min,TIME_DIFF_30min_14h,TIME_DIFF_14h_16h,TIME_DIFF_16h_Bedtime
0,ACE-0044,Male,38.0,1.70,74.00,25.6,Control,Arabe,25 000 - 50 000,25 000 - 50 000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ACE-0087,Male,26.0,1.87,NaN,NaN,Control,Blanc,0 - 25000,0 - 25000,...,NaN,09:53:00,37540.0,50760.0,58050.0,81740.0,1960.0,13220.0,7290.0,23690.0
2,ACE-0023,Male,38.0,1.80,86.18,26.6,ACE,Blanc,0 - 25000,0 - 25000,...,NaN,06:36:00,26560.0,NaN,NaN,82200.0,2800.0,NaN,NaN,NaN
3,ACE-0082,Male,22.0,1.96,84.00,21.9,ACE,Noir,0 - 25000,0 - 25000,...,NaN,07:40:00,29400.0,51600.0,58800.0,81600.0,1800.0,22200.0,7200.0,22800.0
4,ACE-0045,Male,28.0,1.81,73.00,22.3,ACE,Amérique latine,0 - 25000,0 - 25000,...,NaN,07:30:40,29040.0,50760.0,57630.0,76700.0,2000.0,21720.0,6870.0,19070.0